Update installation.md.
ansible/ansible-dev-tools pull request #145
Opened 2024-04-01 16:55 UTC by tima

Updated version numbers in usage section to reflect what is in the README.

2024-04-04 10:54 UTC, audgirka approved these changes

2024-04-08 11:52 UTC, ssbarnea requested changes
We can do this with code.

2024-04-08 11:52 UTC, ssbarnea requested changes
We can do this with code.

2024-04-08 11:57 UTC, ssbarnea approved these changes

2024-04-08 12:15 UTC, merged